name: Deploy Image

on:
  workflow_run:
    workflows: ["Release (Manually)"]
    types:
      - completed

jobs:
  task:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: homelab-toolchain/.github_shared/.github/workflows/create_image.yml@main