name: Manual Release Image

on:
  workflow_dispatch:  

jobs:
  docker:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Get Latest Tag
        id: get_version
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          REPO_NAME=$(basename ${{ github.repository }})
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "Docker Image Name: ghcr.io/${{ github.repository_owner }}/$REPO_NAME:$VERSION"

      - name: Build Docker Image
        run: |
          cd src/
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:${{ env.VERSION }} .
          docker tag ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:${{ env.VERSION }} ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:latest
          cd ..

      - name: Push Docker Image to GitHub Packages
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}:latest